name: postgres_tfg
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: planificador_basket_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d planificador_basket_db"]
      interval: 10s
      timeout: 5s
      retries: 15
