name: postgres_tfg
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: planificador_basket_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata_tfg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d planificador_basket_db"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  pgdata_tfg:
